version: '3.8'

services:
  web:
    build: .
    container_name: flask_app
    restart: always
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - .:/app 
    working_dir: /app  # Set the working directory
    environment:
      - FLASK_ENV=development  # Optional: Set Flask to development mode for auto-reload
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      # Add Neo4j connection details as environment variables
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
    depends_on:
      - neo4j

  neo4j:
    image: neo4j:4.4
    container_name: neo4j_db
    restart: always
    env_file:
      - .env
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
      - NEO4J_dbms_memory_pagecache_size=2G
      - NEO4J_dbms_memory_heap_initial__size=4G
      - NEO4J_dbms_memory_heap_max__size=4G
    ports:
      - "7474:7474"   # Neo4j Browser
      - "7687:7687"   # Bolt protocol
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/var/lib/neo4j/plugins

volumes:
  neo4j_data:
    driver: local
  neo4j_logs:
    driver: local
  neo4j_import:
    driver: local
  neo4j_plugins:
    driver: local
